### ISSUE TITLE
No module named 'pymongo'

### ISSUE THREAD

**Issue by suprix** [cookkkie/mee6#154]
When I try to run python3 app.py it gives me this error:

``
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    import pymongo
ImportError: No module named 'pymongo'
``

**Comment by SilBoydens** [comment]
did you do a `pip install -r /chat-bot/requirements.txt` and the same for the requriements file in website folder?

if you already did that then just do a pip install pymongo

**Comment by suprix** [comment]
Requirement already satisfied: pymongo in /usr/local/lib/python2.7/dist-packages
r

**Comment by suprix** [comment]
When I do  ``pip install -r /chat-bot/requirements.txt`` it gives me this error: http://prntscr.com/hqln1i

**Comment by SilBoydens** [comment]
i might have made a typo, pls use tab completion to have the correct file

**Comment by suprix** [comment]
It's correct directory "chat-bot/requirements.txt" but still that error

**Comment by suprix** [comment]
Alright I installed it

**Comment by suprix** [comment]
![image](https://user-images.githubusercontent.com/24485754/34264134-26ccdbc6-e672-11e7-90e9-12a3366ef200.png)

**Comment by suprix** [comment]
when I try to run python3 bot.py, I am getting similar error as well:

```
Traceback (most recent call last):
  File "bot.py", line 1, in <module>
    from mee6 import Mee6
  File "/root/discord/mee6/chat-bot/mee6.py", line 1, in <module>
    import discord
ImportError: No module named 'discord'
```

**Comment by voidpirate** [comment]
I looked into this a bit (getting up to speed on this project).

The `requirements.txt` doesn't contain the discord library directly you'll have to install it manually by doing: `python3 -m pip install -U discord.py`. The `Dockerfile` is installing the discord library using a local fork see [here](https://github.com/cookkkie/mee6/blob/master/chat-bot/Dockerfile#L10), you can run this command instead of the other one I pasted. Have you tried running the Dockerfile on your machine yet? If you're not using Docker I'd recommend using virtualenv at a minimum at least.

side-note: It might make sense to put the discord library in the `requirements.txt` file actually, since it is a requirement.

/cc @cookkkie
