### ISSUE TITLE
How to self-host?

### ISSUE THREAD

**Issue by wolfbun** [cookkkie/mee6#65]
I know mee6 is open source but when i try to host him myself I get stuck, I downloaded python and I self host another bot, but what I did for that bot doesn't seem to be working for mee6 

was he not meant to be self-hosted?

**Comment by SilBoydens** [comment]
you can selfhost but it is currently really dificult, for as far as i understeand it will be easyer in the future, once it is completly on https://github.com/Mee6 (currently only the streamer plugin is on there)

**Comment by lamepenguins** [comment]
Any official word?

**Comment by Shuugo** [comment]
It would be nice to have some basic documentation on how this is supposed to run.

After 4-5 hours investigating, I could figure how to get some modules running. I even got the Mee6 Ready screen and the bot come online, but it's just not replying to any input. Setting the DEBUG variable to 1 I could find that the bot is able to read the messages, but it just doesn't react to them.

I'm probably missing something important, because it's all done with guesswork and trying to figure how the code works. Also I couldn't get the website to accept connections even though the docker was running fine.

Questions that got after trial and error are:

- Are all parts of the software supposed to run in docker? Not every folder has a Dockerfile.

- Something missing from chat-bot Dockerfile? Without removing the FROM line in the dockerfile you can not get it to build properly. It's pointing to a private repo of ffmpeg that I couldn't find anywhere.

- Are any parts of the software that aren't essential for running? Like for example I can see the carbonitex-agent being optional, but I'm not sure about some of the rest.

In any case, thanks in advance. Any help would be really welcome.

**Comment by MrRedAmber** [comment]
Did you properly give your bot instance permissions to post messages to a channel when you crafted your OAUTH2 invite url?

https://discordapp.com/developers/docs/topics/permissions <- documentation on permissions for bots

https://discordapi.com/permissions.html <- This is the permissions calculator I use to give my bots the proper permissions they need to function in my guild.

**Comment by dynomite567** [comment]
I don't think it's the perms, he could have easily created a bot group that has write perms. This guy has done like everything but I could be wrong.

**Comment by MrRedAmber** [comment]
@Shuugo Can you please post your discord log?

**Comment by SilBoydens** [comment]
@Shuugo docker is not required, you can run it without docker
@all the interested persons: i will spend my day today to make some documentation on this (only took wel over a month to get it working for me)

**Comment by Shuugo** [comment]
@MrRedAmber Yes, the bot had all the permissions assigned. I think the problem resides in another place as the bot was just not replying to even static commands. What log do you want exactly? The one of chat-bot instance that gives the "Mee6 Ready" screen?

@SilBoydens Thank you so much. I really appreciate it.

**Comment by MrRedAmber** [comment]
@Shuugo Yes.

**Comment by Shuugo** [comment]
INFO:discord:Loading plugin Commands.
INFO:discord:Registered 0 commands / 0 bg tasks
INFO:discord:Plugin Commands loaded.
INFO:discord:Loading plugin Help.
INFO:discord:Registered 0 commands / 0 bg tasks
INFO:discord:Plugin Help loaded.
INFO:discord:Loading plugin Levels.
INFO:discord:Registered 2 commands / 0 bg tasks
INFO:discord:Plugin Levels loaded.
INFO:discord:Loading plugin Welcome.
INFO:discord:Registered 0 commands / 0 bg tasks
INFO:discord:Plugin Welcome loaded.
INFO:discord:Loading plugin Moderator.
INFO:discord:Registered 6 commands / 0 bg tasks
INFO:discord:Plugin Moderator loaded.
INFO:discord:Loading plugin Messages.
INFO:discord:Registered 0 commands / 0 bg tasks
INFO:discord:Plugin Messages loaded.
INFO:discord:Loading plugin Music.
INFO:discord:Registered 7 commands / 0 bg tasks
INFO:discord:Plugin Music loaded.
INFO:discord:Loading plugin Search.
INFO:discord:Registered 7 commands / 0 bg tasks
INFO:discord:Plugin Search loaded.
INFO:discord:Loading plugin BasicLogs.
INFO:discord:Registered 0 commands / 0 bg tasks
INFO:discord:Plugin BasicLogs loaded.
INFO:discord:Loading plugin AsciiWelcome.
INFO:discord:Registered 0 commands / 0 bg tasks
INFO:discord:Plugin AsciiWelcome loaded.
INFO:discord:Loading plugin Mee6Game.
INFO:discord:Registered 0 commands / 0 bg tasks
INFO:discord:Plugin Mee6Game loaded.
INFO:discord.client:logging in using static token
INFO:discord.gateway:Created websocket connected to wss://gateway.discord.gg?encoding=json&v=6
INFO:discord.gateway:sent the identify payload to create the websocket
INFO:discord:Connected to the database

 __  __             __    _____                _
|  \/  |           / /   |  __ \              | |
| \  / | ___  ___ / /_   | |__) |___  __ _  __| |_   _
| |\/| |/ _ \/ _ \ '_ \  |  _  // _ \/ _` |/ _` | | | |
| |  | |  __/  __/ (_) | | | \ \  __/ (_| | (_| | |_| |
|_|  |_|\___|\___|\___/  |_|  \_\___|\__,_|\__,_|\__, |
                                                  __/ |
                                                 |___/

   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |H|i|,|I|'|m|M|r|.|M|e|e|6|!|L|o|o|k|a|t|m|e|!|
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

**Comment by MrRedAmber** [comment]
@Shuugo, Sorry I forgot to ask you to send a test message in which Mee6 is supposed to respond.

**Comment by Shuugo** [comment]
> DEBUG:discord:No Datadog agent found...
> DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"t":"TYPING_START","s":3,"op":0,"d":{"user_id":"146684407816781825","timestamp":1493384940,"channel_id":"146684606295441408"}}')
> DEBUG:discord.client:Dispatching event socket_raw_receive
> DEBUG:discord.gateway:WebSocket Event: {'d': {'user_id': '146684407816781825', 'channel_id': '146684606295441408', 'timestamp': 1493384940}, 'op': 0, 's': 3, 't': 'TYPING_START'}
> DEBUG:discord.client:Dispatching event socket_response
> DEBUG:discord.client:Dispatching event typing
> DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"t":"MESSAGE_CREATE","s":4,"op":0,"d":{"type":0,"tts":false,"timestamp":"2017-04-28T13:09:01.174000+00:00","pinned":false,"nonce":"307503472809345024","mentions":[],"mention_roles":[],"mention_everyone":false,"id":"307503473304272896","embeds":[],"edited_timestamp":null,"content":"!help","channel_id":"146684606295441408","author":{"username":"Shuugo","id":"146684407816781825","discriminator":"6669","avatar":"5b2c5387099fedd968f4fa51053f6b1b"},"attachments":[]}}')
> DEBUG:discord.client:Dispatching event socket_raw_receive
> DEBUG:discord.gateway:WebSocket Event: {'d': {'tts': False, 'type': 0, 'nonce': '307503472809345024', 'pinned': False, 'mention_roles': [], 'mention_everyone': False, 'embeds': [], 'mentions': [], 'attachments': [], 'edited_timestamp': None, 'content': '!help', 'author': {'avatar': '5b2c5387099fedd968f4fa51053f6b1b', 'discriminator': '6669', 'id': '146684407816781825', 'username': 'Shuugo'}, 'channel_id': '146684606295441408', 'timestamp': '2017-04-28T13:09:01.174000+00:00', 'id': '307503473304272896'}, 'op': 0, 's': 4, 't': 'MESSAGE_CREATE'}
> DEBUG:discord.client:Dispatching event socket_response
> DEBUG:discord.client:Dispatching event message
> DEBUG:discord:No Datadog agent found...
> DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"t":"TYPING_START","s":5,"op":0,"d":{"user_id":"146684407816781825","timestamp":1493384942,"channel_id":"146684606295441408"}}')
> DEBUG:discord.client:Dispatching event socket_raw_receive
> DEBUG:discord.gateway:WebSocket Event: {'d': {'user_id': '146684407816781825', 'channel_id': '146684606295441408', 'timestamp': 1493384942}, 'op': 0, 's': 5, 't': 'TYPING_START'}
> DEBUG:discord.client:Dispatching event socket_response
> DEBUG:discord.client:Dispatching event typing
> DEBUG:discord:No Datadog agent found...
> DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"t":"MESSAGE_CREATE","s":6,"op":0,"d":{"type":0,"tts":false,"timestamp":"2017-04-28T13:09:03.575000+00:00","pinned":false,"nonce":"307503482867286016","mentions":[],"mention_roles":[],"mention_everyone":false,"id":"307503483374927874","embeds":[],"edited_timestamp":null,"content":"!rank","channel_id":"146684606295441408","author":{"username":"Shuugo","id":"146684407816781825","discriminator":"6669","avatar":"5b2c5387099fedd968f4fa51053f6b1b"},"attachments":[]}}')
> DEBUG:discord.client:Dispatching event socket_raw_receive
> DEBUG:discord.gateway:WebSocket Event: {'d': {'tts': False, 'type': 0, 'nonce': '307503482867286016', 'pinned': False, 'mention_roles': [], 'mention_everyone': False, 'embeds': [], 'mentions': [], 'attachments': [], 'edited_timestamp': None, 'content': '!rank', 'author': {'avatar': '5b2c5387099fedd968f4fa51053f6b1b', 'discriminator': '6669', 'id': '146684407816781825', 'username': 'Shuugo'}, 'channel_id': '146684606295441408', 'timestamp': '2017-04-28T13:09:03.575000+00:00', 'id': '307503483374927874'}, 'op': 0, 's': 6, 't': 'MESSAGE_CREATE'}
> DEBUG:discord.client:Dispatching event socket_response
> DEBUG:discord.client:Dispatching event message
> DEBUG:discord:No Datadog agent found...
> DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"t":"TYPING_START","s":7,"op":0,"d":{"user_id":"146684407816781825","timestamp":1493384944,"channel_id":"146684606295441408"}}')
> DEBUG:discord.client:Dispatching event socket_raw_receive
> DEBUG:discord.gateway:WebSocket Event: {'d': {'user_id': '146684407816781825', 'channel_id': '146684606295441408', 'timestamp': 1493384944}, 'op': 0, 's': 7, 't': 'TYPING_START'}
> DEBUG:discord.client:Dispatching event socket_response
> DEBUG:discord.client:Dispatching event typing
> DEBUG:discord:No Datadog agent found...
> DEBUG:discord:No Datadog agent found...
> DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"t":"PRESENCE_UPDATE","s":8,"op":0,"d":{"user":{"username":"Drakeo","id":"119841375108857858","discriminator":"3078","avatar":"7fba26cf6e6b365628b395bd5e3677d7"},"status":"online","roles":[],"nick":null,"guild_id":"146684606295441408","game":null}}')
> DEBUG:discord.client:Dispatching event socket_raw_receive
> DEBUG:discord.gateway:WebSocket Event: {'d': {'nick': None, 'status': 'online', 'roles': [], 'guild_id': '146684606295441408', 'user': {'avatar': '7fba26cf6e6b365628b395bd5e3677d7', 'discriminator': '3078', 'id': '119841375108857858', 'username': 'Drakeo'}, 'game': None}, 'op': 0, 's': 8, 't': 'PRESENCE_UPDATE'}
> DEBUG:discord.client:Dispatching event socket_response
> DEBUG:discord.client:Dispatching event member_update
> DEBUG:discord.client:Dispatching event typing
> DEBUG:discord:No Datadog agent found...
> DEBUG:websockets.protocol:client << Frame(fin=True, opcode=1, data=b'{"t":"MESSAGE_CREATE","s":11,"op":0,"d":{"type":0,"tts":false,"timestamp":"2017-04-28T13:23:22.200000+00:00","pinned":false,"nonce":"307507084230918144","mentions":[],"mention_roles":[],"mention_everyone":false,"id":"307507084709199872","embeds":[],"edited_timestamp":null,"content":"!levels","channel_id":"146684606295441408","author":{"username":"Shuugo","id":"146684407816781825","discriminator":"6669","avatar":"5b2c5387099fedd968f4fa51053f6b1b"},"attachments":[]}}')
> DEBUG:discord.client:Dispatching event socket_raw_receive
> DEBUG:discord.gateway:WebSocket Event: {'d': {'tts': False, 'type': 0, 'nonce': '307507084230918144', 'pinned': False, 'mention_roles': [], 'mention_everyone': False, 'embeds': [], 'mentions': [], 'attachments': [], 'edited_timestamp': None, 'content': '!levels', 'author': {'avatar': '5b2c5387099fedd968f4fa51053f6b1b', 'discriminator': '6669', 'id': '146684407816781825', 'username': 'Shuugo'}, 'channel_id': '146684606295441408', 'timestamp': '2017-04-28T13:23:22.200000+00:00', 'id': '307507084709199872'}, 'op': 0, 's': 11, 't': 'MESSAGE_CREATE'}
> DEBUG:discord.client:Dispatching event socket_response
> DEBUG:discord.client:Dispatching event message
> DEBUG:discord:No Datadog agent found...
> DEBUG:discord:No Datadog agent found...

**Comment by MrRedAmber** [comment]
@Shuugo, I think your Mee6 is faulting when it tries to update DataDog (since you don't have a DD instance configured) stats in this method in `mee6.py`:
```python
async def on_message(self, message):
        self.stats.incr('mee6.recv_messages')
        if message.channel.is_private:
            return
        if message.author.__class__ != discord.Member:
            return

        server = message.server

        if message.content == "!shard?":
            if hasattr(self, 'shard_id'):
                await self.send_message(
                    message.channel,
                    "shard {}/{}".format(self.shard_id+1, self.shard_count)
                )

        enabled_plugins = await self.get_plugins(server)
        for plugin in enabled_plugins:
            self.loop.create_task(plugin._on_message(message))
```
Try and comment out this line in `mee6.py` and try the `!help` command
```python
    self.stats.incr('mee6.recv_messages')
```

**Comment by Shuugo** [comment]
It didn't work, same result.

I'll try either waiting for the documentation or setting up datadog, see if that makes any sensible change. Since datadog warning doesn't appear when DEBUG is disabled, I don't think it should be a critical error, but will give it a shot.

If I manage to set up datadog I'll report back.

**Comment by MrRedAmber** [comment]
@Shuugo Okay, could you possibly push your source to a remote branch on your forked repository of mee6? ( for reproducing purposes )

**Comment by SilBoydens** [comment]
DOCS: http://mee6.github.io/Mee6-documentation/self-hosting/
only took me a full day to figure out how i did it last time.
for any questions pls contact me (Sil#5262) in the Mee6 support server (http://discord.gg/mee6)

**Comment by dynomite567** [comment]
Great, thanks @SilBoydens this will be useful with my experiments with mee6!

**Comment by Shuugo** [comment]
Thanks for the docs @SilBoydens, I'll experiment with it later in a clean VPS session.

**Comment by Shuugo** [comment]
Got it working with your instructions! Thank you very much.

For the website bit if anyone cares: I couldn't manage to load it outside the localhost realm, so I installed Nginx with proxy_pass to localhost:5000.

**Comment by cookkkie** [comment]
@dynomite567 tfw I saw your comment and thought: " wuuut, I never wrote that " haha 😆

**Comment by dynomite567** [comment]
Lol, guess I'm another rick from another dimension 😂

**Comment by IVTimVI** [comment]
@SilBoydens thanks m8, i appreciate the instructions

**Comment by TheExplodingGiraffe** [comment]
@wolfbun Not really a answer but what bot actually worked for you? because i want to have a own hosted bot! :D

**Comment by IVTimVI** [comment]
@TheExplodingGiraffe yup, it worked

**Comment by TheExplodingGiraffe** [comment]
@IVTimVI do you know any other bots that i can host my self that are easier to get working?

**Comment by IVTimVI** [comment]
@TheExplodingGiraffe NadekoBot

**Comment by TheExplodingGiraffe** [comment]
@IVTimVI ok thanks i will try that know! :D

**Comment by IVTimVI** [comment]
@TheExplodingGiraffe its really easy, follow the instructions that they have

**Comment by etbamn** [comment]
@SilBoydens @cookkkie How to make ourselves an Admin to unbuff Music plugin and use it on multiple Discord servers?

**Comment by cookkkie** [comment]
`redis-cli` `set user:{your_discord_user_id}:points 99999`

**Comment by etbamn** [comment]
@SilBoydens @cookkkie How to make ourselves an Admin to bypass Music plugin buff limitation and use it on multiple Discord servers?

**Comment by etbamn** [comment]
@cookkkie Okay Thank You :)

**Comment by Codfish246** [comment]
@SilBoydens I was testing mee6 and On running the website app.py, i get an error in app.py line 44 db = redis.Redis.from_url(REDIS_URL, decode_responses=True)
TypeError: a bytes-like object is required, not 'str'
Know anything about this?

**Comment by SilBoydens** [comment]
nope, Mee6 has changed a lot in the last half year, i have no clue how to set it up now

**Comment by ChisdealHD** [comment]
I'm getting error of this

chisdealhd@Gaming-PC:~/mee6$ cd chat-bot && python3 bot.py
Traceback (most recent call last):
  File "bot.py", line 37, in <module>
    sentry_dsn=sentry_dsn)
  File "/home/chisdealhd/mee6/chat-bot/mee6.py", line 30, in __init__
    self.db = Db(self.redis_url, self.mongo_url, self.loop)
  File "/home/chisdealhd/mee6/chat-bot/database.py", line 16, in __init__
    self.redis_address = parse_redis_url(redis_url)
  File "/home/chisdealhd/mee6/chat-bot/utils.py", line 8, in parse_redis_url
    result = re.match(pattern, redis_url).groups()
  File "/usr/lib/python3.5/re.py", line 163, in match
    return _compile(pattern, flags).match(string)
TypeError: expected string or bytes-like object
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending coro=<Db.create() running at /home/chisdealhd/mee6/chat-bot/database.py:18>>
/usr/lib/python3.5/asyncio/base_events.py:412: RuntimeWarning: coroutine 'Db.create' was never awaited
ERROR:asyncio:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fea7b5a4f28>

**Comment by ChisdealHD** [comment]
this my first time setup mee6 bot as self hosting

**Comment by SilBoydens** [comment]
your redis database is not set correct, if you can't figure taht out from the error it gives then i don't think you will be able to host Mee6 yourself

**Comment by Brramble** [comment]
when running the bot:

`Traceback (most recent call last):
  File "bot.py", line 1, in <module>
    from mee6 import Mee6
  File "/root/mee6/chat-bot/mee6.py", line 8, in <module>
    from database import Db
  File "/root/mee6/chat-bot/database.py", line 2, in <module>
    import motor.motor_asyncio
ImportError: No module named 'motor'
`

When running the website:
`Traceback (most recent call last):
  File "app.py", line 1027, in <module>
    from mee6.plugins import Timers
  File "/usr/local/lib/python3.5/dist-packages/mee6/plugins/__init__.py", line 11, in <module>
    from mee6.plugins.search import Search
ImportError: No module named 'mee6.plugins.search'
`

**Comment by ChisdealHD** [comment]
@Brramble im still new setting up and that errored me out while installing it and idk imposable run it now. no docs setup part that other docs someone methered and that wasnt useful tell more setup

**Comment by ChisdealHD** [comment]
i coded mine main bot as nodejs custom coded but theres bug on skip command i cant fix that so i was thinking use mee6 and custom plugins more.

**Comment by jtagt** [comment]
@SilBoydens I'm having trouble starting the website because I don't have the mee6 module. know how I can get that?

**Comment by SilBoydens** [comment]
not, private repo, won't come public
https://cdn.discordapp.com/attachments/302245580673908740/402735776317571072/unknown.png
if you want to selfhost then either change some stuff so you don't need that module anymore or use a older commit (in both cases you need to change stuff as the older commits don't work anymore with changes to other stuff)

**Comment by jtagt** [comment]
@SilBoydens what did the module do?

**Comment by jtagt** [comment]
WARNING:schwifty:[Errno 111] Connect call failed ('127.0.0.1', 8080) Cannot connect to schwifty. Retrying.
Ignoring exception in on_socket_raw_receive
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/home/jtagt/mee6/chat-bot/mee6.py", line 89, in on_socket_raw_receive
    tags = {'op': str(payload['op']),
TypeError: string indices must be integers



what does that mean

**Comment by SilBoydens** [comment]
that means that you can't connect to the voice module (music and record) wich runs seperate from the normal bot and is not public ~~yet~~

**Comment by jtagt** [comment]
oof

**Comment by jtagt** [comment]
its causing the bot to not function correctly

**Comment by jtagt** [comment]
but man that sucks that the github mee6 module is private
